on: push
jobs:
  code-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@master
        with:
          go-version: 1.13.x

      - uses: actions/checkout@master

      - run: go get -v -t -d ./...

      - run: go test ./...
